modules/bekofis/models/News.php
<?php

namespace app\modules\bekofis\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\User;
use app\components\THelper;
/**
 * This is the model class for table "crm_news_posts".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $language_id
 * @property integer $category_id
 * @property integer $status
 * @property integer $post_at
 * @property integer $user_id
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $rememberMe;
    public $hours;
    public $minutes;

    public static function tableName()
    {
        return 'crm_news_posts';
    }
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['post_at','title','description'],'required'],
            [['description'], 'string'],
            [['created_at', 'updated_at', 'language_id', 'category_id', 'status'], 'integer'],
            [['post_at', 'created_at', 'updated_at', 'rememberMe', 'hours', 'minutes', 'user_id'], 'safe'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => THelper::t('id'),
            'title' => THelper::t('topic_news'),
            'description' => '',
            'created_at' => THelper::t('created'),
            'updated_at' => THelper::t('updated'),
            'language_id' => THelper::t('language_id'),
            'category_id' =>THelper::t('category_id') ,
            'status' => THelper::t('status'),
            'post_at' => THelper::t('date'),
            'rememberMe' => '',
            'hours' => '',
            'minutes' => '',
        ];
    }

    public function getNewsUser()
    {
        return $this->hasMany(SeenNews::className(), ['news_id' => 'id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])->via('newsUser');
    }
}

modules/bekofis/controllers/NewsController.php
<?php

namespace app\modules\bekofis\controllers;
use Yii;
use yii\web\Controller;
use app\modules\settings\models\Localisation;
use app\modules\bekofis\models\News;
use yii\filters\VerbFilter;

class NewsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $model = new News();
        $language = Localisation::find()->select('id')->where('prefix=:id', [':id' =>Yii::$app->language])->one();
        if($model->load(Yii::$app->request->post())) {
            if($model->rememberMe == 1) {
                $post_at = $model->post_at.' '.$model->hours.':'.$model->minutes.':00';
                $model->post_at = strtotime($post_at);
            } else {
                $post_at = $model->post_at.' '.'00'.':'.'01'.':00';
                $model->post_at = strtotime($post_at);
            }
            $model->language_id = $language->id;
            $model->user_id = Yii::$app->user->identity['id'];
            if($model->save()) {
                return $this->refresh();
            }
        }

        return $this->render('index',[
            'model'=>$model,
        ]);
    }

    public function actionNews()
    {
        return $this->renderPartial('news');
    }
}

modules/bekofis/views/news/index.php
<?php

/* @var $this yii\web\View
 * @var $i
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use app\components\THelper;
//use kartik\date\DatePicker;
//use app\assets\AppAsset;

//AppAsset::register($this);

$this->title = THelper::t('news');
Yii::$app->session->getFlash('error');
?>

<div class="email-list-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="form-inline">
        <?= Html::label(THelper::t('date'), 'post_at', ['class' => 'control-label', 'style' => 'float:left; margin: 8px 69px 0px 0px;']) ?>
        <?= $form->field($model, 'post_at')->textInput([
                'maxlength'=>16, 'class'=>'input-sm input-s datepicker-input form-control',
                'data-date-format'=>'dd-mm-yyyy'
            ])->label(false) ?>

        <?= $form->field($model, 'rememberMe')->checkbox(['class' =>'normal', 'style' => 'margin-top: 10px'])
            ->label(THelper::t('time'), ['class' => 'control-label', 'style' => 'float:left; margin: 6px 5px 0px 0px;'])?>

        <?php $mas = array();
            for($i = 0; $i <= 23; $i++) { $mas[]= $i;}
            echo $form->field($model, 'hours')->dropDownList($mas, ['class'=>'input-sm', 'style'=>'background:#FFF'])
                ->label(THelper::t('h')/*'ч.'*/, ['style' => 'float: right; margin: 8px 0px 0px 3px;']); ?>

        <?php $mas = array();
            for($i = 0; $i <= 59; $i++) { $mas[]= $i;}
            echo $form->field($model, 'minutes')->dropDownList($mas, ['class'=>'input-sm', 'style'=>'background:#FFF'])
                ->label(THelper::t('min'), ['style' => 'float: right; margin: 8px 0px 0px 3px;']); ?>

    </div>

    <?= Html::label(THelper::t('topic_news'), 'title', ['class' => 'control-label', 'style' => 'float:left; margin: 8px 10px 0px 0px;']) ?>
        <?= $form->field($model, 'title')->textInput(['maxlength' => 255, 'style' => 'width:40%'])->label(false) ?>

    <?= $form->field($model, 'description')->widget(CKEditor::className(),[
        'editorOptions' => [
            'preset' => 'full',
            'inline' => false,
        ],
    ]);
    ?>

    <?= Html::a(THelper::t('preview'), ['news/news'], ['data-toggle'=>'ajaxModal', 'class' => 'btn btn-primary pull-left', 'name' => 'preview', 'id' => 'preview']); ?>
    <?= Html::submitButton(THelper::t('save_changes'), ['class' => 'btn btn-info pull-right', 'name' => 'save_news']) ?>
    <?php ActiveForm::end(); ?>
    <br><br><br><br>

</div>

<?php $this->registerJsFile('js/datepicker/bootstrap-datepicker.js',['depends'=>['app\assets\AppAsset']]); ?>
<?php $this->registerJsFile('js/main/news.js',['depends'=>['app\assets\AppAsset']]); ?>

modules/bekofis/views/news/news.php
<?php

/* @var $this yii\web\View */
/* @var $text */
/* @var $title */

use yii\helpers\Html;

$this->title = 'Новости';

?>

<div class="modal-dialog" style="word-wrap: break-word;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h4 class="modal-title"><h6 class="time_to_show"></h6></h4>
        </div>
        <div class="modal-body">
            <div class="users-create">
               <h3 class="titl" style="text-align: center;"></h3>
               <h5 class="cont"></h5>
            </div>
        </div>
    </div>
</div>